language: perl
sudo: false
perl:
  - "5.8.1"
  - "5.8.3"
  - "5.8.6"
  - "5.8.7"
  - "5.8.8"
  - "5.8.9"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

